### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by hnustwjj** [yusixian/cosine-music#1]
试试unocss或者windicss吧，用法差不多，但是支持attr mode，不会有很长一串class的情况

**Comment by yusixian** [comment]
> 试试unocss或者windicss吧，用法差不多，但是支持attr mode，不会有很长一串class的情况

好提议，但是目前不会很长的class，有的话就是我还没封装好，而且tailwind也可以通过配置解决这个问题（
Tailwind 及其相关生态使用的足够熟练了，并且实际使用也没遇到什么坑，作为一个优先搞出mvp版本为主的毕设就没必要再上unocss了，而windicss之前写组件库时调研过，生态不太行~
